### ISSUE TITLE
it is uttermostly useless

### ISSUE THREAD

**Issue by Piggywiggy-The-Zhu** [kev1nweng/Myphlex#1]
The memory of every password is the joie de vivre 'cause my password consists my dearest's name which touchs my heart. Not only myself but also many people enjoy the process of typing their valuable memory in such way.Meantime,IOS does it better.

**Comment by Piggywiggy-The-Zhu** [comment]
Hear hear

**Comment by kev1nweng** [comment]
Imagine what happens when you save a password on iCloud keyring and have to reach for an iPhone every time when you try to log in on a pc

**Comment by kev1nweng** [comment]
Btw you can put whatever special to you in the password prefix or suffix. It's actually fairly customizable
